### PR TITLE
Do not crash on bad data [CH8438]

### PR DESCRIPTION
**Pull request by dcsobral**

### CODE REVIEW

**Comment by alissapajer** [comment]
[CH8437]

**Comment by alissapajer** [comment]
haha now I broke everything by associating the wrong story, sorry :)

**Comment by alissapajer** [comment]
Or maybe not? Idk, @dcsobral I won't touch it again so you can get it in the right state.

**Comment by alissapajer** [comment]
oooo you have two PRs open, that's why I got confused

**Review by nicflores — APPROVED** [review]

**Pull request merged**
